language: python
env:
    - TOX_ENV=py26
    - TOX_ENV=py27

install:
    - travis_retry pip install tox coveralls
    - travis_retry sudo npm install -g

script:
    - tox -e $TOX_ENV
    - grunt --verbose

after_success:
    - if [[ $TOX_ENV = "py27" ]]; then travis_retry pip install coveralls; coveralls -i; fi
